"""
重要な発見: 起動順序による動作の違い

【確認された事実】
✓ ラズパイ起動 → その後カウンターボード接続 = 正常動作
✗ カウンターボード接続済み → ラズパイ起動 = 電源異常 (推測)

【この現象が示すこと】
起動シーケンスに問題がある可能性

【考えられる原因】
"""

print("=" * 70)
print("起動順序による電源異常の分析")
print("=" * 70)
print()

print("【確認された動作パターン】")
print()
print("パターンA: ラズパイ起動後にカウンターボード接続")
print("  1. ラズパイに電源投入")
print("  2. ラズパイ起動完了")
print("  3. カウンターボードの電源接続 (3.3V + GND)")
print("  → 結果: ✓ 正常動作、電圧正常、カウンタ動作OK")
print()
print("パターンB: カウンターボード接続済みでラズパイ起動 (推測)")
print("  1. カウンターボード接続済み")
print("  2. ラズパイに電源投入")
print("  → 結果: ✗ 電源異常 (5V→0V, 3.3V→4V)?")
print()

print("=" * 70)
print("原因の可能性")
print("=" * 70)
print()

print("【可能性1: 起動時のGPIO初期状態（★最有力★）")
print()
print("ラズパイの起動シーケンス:")
print()
print("  電源投入直後:")
print("    └→ GPIOピンが不定状態またはデフォルト設定")
print("       └→ 一部のピンが出力モード + HIGH")
print("          └→ 5V出力またはハイインピーダンス")
print()
print("  特にD0/D1/D2 (GPIO13/21/25) が:")
print("    - 起動時に一時的にHIGH (5V) を出力")
print("    - または内部プルアップが有効")
print()
print("  このとき:")
print("    GPIO (5V一時出力)")
print("       ↓")
print("    74HC590入力ピン")
print("       ↓")
print("    保護ダイオード")
print("       ↓")
print("    VCC (3.3V)")
print()
print("  結果:")
print("    - 5V → 保護ダイオード (Vf=0.7V) → 4.3V が3.3Vラインに逆流")
print("    - 3.3Vラインが4Vに上昇")
print("    - 5Vラインから大電流が流れて電圧降下 → 0V")
print()
print("  ラズパイ起動完了後:")
print("    - GPIOが正常に初期化される")
print("    - 入力モード + プルダウン (または適切な設定)")
print("    - 問題解消")
print()

print("【可能性2: 電源投入時の突入電流】")
print()
print("ラズパイの電源投入シーケンス:")
print()
print("  1. 5Vライン → 先に立ち上がる")
print("  2. 3.3Vライン → レギュレータ経由で立ち上がる (遅延)")
print()
print("  この間にカウンターボードが接続されていると:")
print()
print("    5V (すでにON)")
print("       ↓ [一時的な経路]")
print("    3.3V (まだ立ち上がり途中)")
print()
print("  特にGPIOピンが不定状態だと:")
print("    - 5Vが信号線経由で3.3Vラインに流入")
print("    - レギュレータが過負荷")
print()

print("【可能性3: I2Cバスの初期化順序】")
print()
print("PCA9685が接続されている場合:")
print()
print("  起動時:")
print("    1. I2Cバス (SDA/SCL) が不定状態")
print("    2. PCA9685が内部で5Vプルアップを試みる")
print("    3. カウンターボード経由で電流が流れる")
print()
print("  ただし:")
print("    - 今回PCA9685は外れている可能性")
print("    - この可能性は低い")
print()

print("=" * 70)
print("診断方法")
print("=" * 70)
print()

print("【テスト1: 起動順序の影響確認】")
print()
print("現在確認済み:")
print("  ✓ ラズパイ起動後 → カウンターボード接続 = 正常")
print()
print("追加確認:")
print("  1. カウンターボード接続済み → ラズパイ起動")
print("     → 電源電圧測定: 5V=___V, 3.3V=___V")
print("     → 異常が再現するか？")
print()
print("  2. ラズパイ起動中の電圧モニタ")
print("     マルチメータで継続測定:")
print("       - 電源投入前: 0V")
print("       - 投入直後: ___V (瞬間的なピーク)")
print("       - 起動中: ___V")
print("       - 起動完了後: ___V")
print()

print("【テスト2: GPIO初期状態の確認】")
print()
print("ラズパイ起動直後にGPIOの状態を確認:")
print()
print("  /boot/config.txt に追加:")
print("    # GPIO初期状態をプルダウンに設定")
print("    gpio=13=pd  # D0")
print("    gpio=21=pd  # D1")
print("    gpio=25=pd  # D2")
print("    gpio=17=pd  # CCLR")
print("    gpio=24=pd  # RCLK")
print()
print("  効果:")
print("    - 起動時からGPIOがプルダウンされる")
print("    - 5Vの逆流を防止")
print()

print("【テスト3: IF基板の電圧波形観察】")
print()
print("オシロスコープまたは高速マルチメータで:")
print()
print("  1. 5Vラインの電圧波形")
print("     起動時の変動を観察")
print()
print("  2. 3.3Vラインの電圧波形")
print("     起動時の変動を観察")
print()
print("  3. D0/D1/D2の電圧波形")
print("     起動時に5V付近に上昇するか確認")
print()

print("=" * 70)
print("対処法")
print("=" * 70)
print()

print("【対策A: GPIO初期状態の設定（★推奨★）")
print()
print("/boot/config.txt に追加:")
print()
print("  # GPIO初期状態をプルダウンに設定")
print("  gpio=13=pd")
print("  gpio=21=pd")
print("  gpio=25=pd")
print("  gpio=17=pd")
print("  gpio=24=pd")
print()
print("設定後:")
print("  sudo reboot")
print()
print("効果:")
print("  - 起動時からGPIOがLOWに固定")
print("  - カウンターボード接続済みでも安全に起動可能")
print()

print("【対策B: 起動スクリプトでGPIO初期化】")
print()
print("/etc/rc.local に追加:")
print()
print("  # GPIO初期化")
print("  echo 13 > /sys/class/gpio/export")
print("  echo in > /sys/class/gpio/gpio13/direction")
print("  echo 21 > /sys/class/gpio/export")
print("  echo in > /sys/class/gpio/gpio21/direction")
print("  echo 25 > /sys/class/gpio/export")
print("  echo in > /sys/class/gpio/gpio25/direction")
print("  echo 17 > /sys/class/gpio/export")
print("  echo in > /sys/class/gpio/gpio17/direction")
print("  echo 24 > /sys/class/gpio/export")
print("  echo in > /sys/class/gpio/gpio24/direction")
print()

print("【対策C: カウンターボードに保護回路追加】")
print()
print("信号ラインに直列抵抗を追加:")
print()
print("  IF基板 D0 ─[1kΩ]─ カウンター D0")
print("  IF基板 D1 ─[1kΩ]─ カウンター D1")
print("  IF基板 D2 ─[1kΩ]─ カウンター D2")
print()
print("効果:")
print("  - 保護ダイオード経由の電流を制限")
print("  - VCC上昇を抑制")
print()
print("注意:")
print("  - 信号遅延が増加する可能性")
print("  - 高速カウントには影響する可能性")
print()

print("【対策D: 電源投入手順の確立】")
print()
print("運用ルール:")
print()
print("  1. ラズパイに電源投入")
print("  2. ラズパイ起動完了を待つ (約30秒)")
print("  3. カウンターボードの電源接続")
print()
print("  または:")
print()
print("  1. カウンターボードの電源スイッチを追加")
print("  2. ラズパイ起動後にON")
print()

print("=" * 70)
print("次のアクション（推奨順）")
print("=" * 70)
print()
print("1. 起動順序の影響確認")
print("   カウンターボード接続済み → ラズパイ起動")
print("   → 電源異常が再現するか確認")
print()
print("2. /boot/config.txt にGPIO初期化設定を追加")
print("   gpio=13=pd")
print("   gpio=21=pd")
print("   gpio=25=pd")
print("   gpio=17=pd")
print("   gpio=24=pd")
print("   → sudo reboot")
print()
print("3. カウンターボード接続済みで再起動テスト")
print("   → 電源異常が解消されるか確認")
print()
print("4. 全システム統合テスト")
print("   ラズパイ + IF基板 + カウンターボード + PCA9685")
print("   → 電圧確認: 5V=5V, 3.3V=3.3V")
print("   → i2cdetect -y 1 で0x40検出")
print("   → test_rpr220_counter.py で動作確認")
print()

print("=" * 70)
print("現在のステータス")
print("=" * 70)
print()
print("✓ カウンターボード: 動作確認完了")
print("✓ RPR220センサ: 動作確認完了")
print("✓ 74HC590: 動作確認完了")
print("✓ IF基板経由接続: 起動後接続で正常動作")
print("⚠ 起動順序: 調査・対策が必要")
print("⚠ PCA9685: 起動順序対策後にテスト")
print()
print("進捗: 約80% (ハードウェア動作確認完了、起動順序対策待ち)")
print()

print("=" * 70)
print("重要な発見")
print("=" * 70)
print()
print("カウンターボードとIF基板には物理的な問題はなく、")
print("ラズパイの起動時のGPIO初期状態が原因と推定されます。")
print()
print("/boot/config.txt の設定追加で恒久的に解決できる可能性が高いです。")
print()
