"""
カウンターボード電源異常の原因分析

【現象】
カウンターボード接続時:
- ラズパイ 5Vライン → 0V に低下
- ラズパイ 3.3Vライン → 4V に上昇

【物理的に起こりうる原因】
"""

print("=" * 60)
print("カウンターボード電源異常の原因分析")
print("=" * 60)
print()

print("【可能性1: 5Vと3.3Vの短絡】")
print()
print("カウンターボード上で5Vラインと3.3Vラインが短絡:")
print()
print("  5V ----短絡---- 3.3V")
print()
print("結果:")
print("  - 両ラインの電圧が平均化される")
print("  - (5V + 3.3V) / 2 ≒ 4V")
print("  - 5V側から見ると低下、3.3V側から見ると上昇")
print()
print("確認方法:")
print("  カウンターボード単体で5Vピン ↔ 3.3Vピンの抵抗測定")
print("  - 短絡している場合: 0Ω～数Ω")
print("  - 正常な場合: 数百kΩ以上")
print()

print("【可能性2: 逆電流（バックパワー）】")
print()
print("カウンターボードの3.3V入力が実は出力になっている:")
print()
print("  カウンターボード 3.3V出力 → ラズパイ 3.3Vライン")
print()
print("同時に:")
print("  カウンターボードが5Vラインから過電流を引き込む")
print("  → ラズパイの5Vレギュレータが保護モードに入り0Vに")
print()
print("可能性:")
print("  - カウンターボードに電源ICがあり、誤配線で出力モードに")
print("  - 昇圧コンバータが3.3V→5Vに昇圧して逆流")
print()

print("【可能性3: GND分離による電位差】")
print()
print("カウンターボードのGNDが他のGNDと分離:")
print()
print("  ラズパイGND --- カウンターボードGND（フロート）")
print()
print("結果:")
print("  - カウンターボードのGNDが浮いている")
print("  - 3.3V入力を基準にGNDが-0.7V程度にシフト")
print("  - 測定すると3.3V+0.7V=4Vに見える")
print()

print("【可能性4: ダイオードの逆接続】")
print()
print("カウンターボードに保護ダイオードが逆向きに実装:")
print()
print("  5V ----|>|---- 3.3V  （ダイオードが逆）")
print()
print("結果:")
print("  - ダイオードのVf(0.7V)分の電圧降下")
print("  - 5V → 4.3V、3.3V → 4V")
print()

print("=" * 60)
print("診断手順")
print("=" * 60)
print()

print("【ステップ1: カウンターボード単体の抵抗測定】")
print()
print("カウンターボードを全て外した状態で:")
print()
print("1. 5Vピン ↔ 3.3Vピンの抵抗")
print("   測定値: _____ Ω")
print("   正常値: >100kΩ")
print("   異常値: <100Ω（短絡）")
print()
print("2. 5Vピン ↔ GNDピンの抵抗")
print("   測定値: _____ Ω")
print("   正常値: 数kΩ～数十kΩ")
print()
print("3. 3.3Vピン ↔ GNDピンの抵抗")
print("   測定値: _____ Ω")
print("   正常値: 数kΩ～数十kΩ")
print()

print("【ステップ2: カウンターボードの目視確認】")
print()
print("以下を重点的に確認:")
print()
print("□ 電源ピンのはんだブリッジ（短絡）")
print("□ ダイオードの向き（カソードマーク）")
print("□ レギュレータICの有無と型番")
print("□ コンデンサの極性（電解コンデンサ）")
print("□ ジャンパ設定（5V/3.3V選択など）")
print()

print("【ステップ3: カウンターボードの回路確認】")
print()
print("カウンターボードに搭載されているICを全て報告:")
print()
print("1. カウンタIC: 74HC590")
print("2. レギュレータIC: _____ （型番は？）")
print("3. その他のIC: _____")
print()
print("特に確認:")
print("  - 電源ICがあるか（AMS1117、LM1117など）")
print("  - その入力・出力ピンの配線")
print()

print("【ステップ4: 配線の確認】")
print()
print("カウンターボードのピン配置:")
print()
print("IF基板から供給されるピン:")
print("  □ VCC (5Vまたは3.3V)")
print("  □ GND")
print("  □ データ信号（D0, D1, D2）")
print("  □ 制御信号（CCLR, RCLK）")
print()
print("特に確認:")
print("  - VCCが5Vピンと3.3Vピンの両方に接続されていないか")
print("  - データ信号ピンが電源ラインに接続されていないか")
print()

print("=" * 60)
print("最も可能性が高い原因")
print("=" * 60)
print()
print("【推測】5Vと3.3Vの直接短絡")
print()
print("カウンターボードの製作時に:")
print("  - 5Vラインと3.3Vラインが意図せず接続")
print("  - はんだブリッジ")
print("  - 配線ミス")
print()
print("結果:")
print("  ラズパイの5V(2A制限) ←短絡→ 3.3V(1A制限)")
print("  → 両方のレギュレータが負荷を分担")
print("  → 中間電圧(約4V)に落ち着く")
print("  → 5V系は電流不足で0Vに低下")
print()

print("=" * 60)
print("対処法")
print("=" * 60)
print()
print("1. カウンターボードの5Vピンと3.3Vピンを確認")
print("   - 導通がある場合は短絡箇所を特定")
print("   - はんだ吸取器で修正")
print()
print("2. 74HC590は3.3V動作可能")
print("   - 5Vラインを使わない設計に変更")
print("   - 3.3VのみでカウンターボードをVCC供給")
print()
print("3. 暫定対策")
print("   - カウンターボードの5Vピンを物理的に切断")
print("   - 3.3VのみでVCC供給")
print()
