"""
システム構成の分析

【接続構成】
ラズパイ（40ピン）
    ↓ 40ピンリボンケーブル
IF基板（インターフェース基板）
    ↓ 分岐
    ├→ PCA9685基板（モータードライバ）
    └→ カウンタボード（74HC590など）

【問題】
- i2cdetect で PCA9685 (0x40) が検出されない
- ラズパイ単体の電源は正常（5V, 3.3V OK）
- PCA9685基板の目視・抵抗測定では異常なし

【原因の可能性】
1. IF基板の問題
2. IF基板→PCA9685間の配線/接続の問題
3. I2C信号の分岐による問題
"""

print("=" * 60)
print("IF基板を含むシステム診断")
print("=" * 60)
print()

print("【現在の状態】")
print("  ラズパイ ←（40ピン外した）→ IF基板 → PCA9685")
print("                                    → カウンタボード")
print()

print("【診断手順】")
print()
print("=" * 60)
print("ステップ1: IF基板の電源確認")
print("=" * 60)
print()
print("ラズパイとIF基板を40ピンで接続した状態で:")
print()
print("1. IF基板上の電源電圧を測定")
print("   IF基板の5Vライン: _____ V（期待値: 5V）")
print("   IF基板の3.3Vライン: _____ V（期待値: 3.3V）")
print("   IF基板のGNDライン: _____ V（期待値: 0V）")
print()
print("2. IF基板→PCA9685への出力電圧")
print("   PCA9685接続コネクタのVCCピン: _____ V")
print("   PCA9685接続コネクタのGNDピン: _____ V")
print()

print("=" * 60)
print("ステップ2: IF基板のI2C信号確認")
print("=" * 60)
print()
print("ラズパイとIF基板を40ピンで接続した状態で:")
print()
print("1. IF基板上のSDA/SCL電圧（アイドル時）")
print("   SDAライン: _____ V（期待値: 3.3V）")
print("   SCLライン: _____ V（期待値: 3.3V）")
print()
print("2. IF基板上のプルアップ抵抗確認")
print("   SDA - 3.3V間の抵抗: _____ Ω（期待値: 4.7kΩ程度）")
print("   SCL - 3.3V間の抵抗: _____ Ω（期待値: 4.7kΩ程度）")
print()
print("※ プルアップがないとI2C通信不可")
print()

print("=" * 60)
print("ステップ3: PCA9685への接続確認")
print("=" * 60)
print()
print("IF基板とPCA9685を接続した状態で:")
print()
print("1. PCA9685のVCCピンの電圧")
print("   測定値: _____ V（期待値: 5Vまたは3.3V）")
print()
print("2. PCA9685のSDA/SCLピンの電圧（アイドル時）")
print("   SDA測定値: _____ V（期待値: 3.3V）")
print("   SCL測定値: _____ V（期待値: 3.3V）")
print()
print("※ 0Vの場合、配線が繋がっていない")
print()

print("=" * 60)
print("ステップ4: IF基板のピン配置確認")
print("=" * 60)
print()
print("IF基板の40ピンコネクタのピン配置を確認:")
print()
print("ラズパイ側の期待値:")
print("  物理2p: 5V")
print("  物理3p: GPIO2 (SDA)")
print("  物理5p: GPIO3 (SCL)")
print("  物理6p: GND")
print()
print("IF基板が正しくラズパイのピンを")
print("PCA9685に転送しているか確認")
print()

print("=" * 60)
print("ステップ5: カウンタボードとの干渉確認")
print("=" * 60)
print()
print("1. カウンタボードを外した状態でテスト")
print("   - IF基板 + PCA9685のみ接続")
print("   - i2cdetect -y 1 を実行")
print("   - 0x40が検出されるか？")
print()
print("2. カウンタボードがI2Cバスを使用しているか確認")
print("   - カウンタボードにI2Cデバイスがあるか")
print("   - アドレス競合の可能性")
print()

print("=" * 60)
print("ステップ6: 直接接続テスト")
print("=" * 60)
print()
print("IF基板を経由せず、ラズパイとPCA9685を直接接続:")
print()
print("必要な配線:")
print("  ラズパイ物理2p (5V)    → PCA9685 VCC")
print("  ラズパイ物理3p (SDA)   → PCA9685 SDA")
print("  ラズパイ物理5p (SCL)   → PCA9685 SCL")
print("  ラズパイ物理6p (GND)   → PCA9685 GND")
print()
print("この状態で i2cdetect -y 1 を実行")
print()
print("結果:")
print("  - 0x40検出される → IF基板に問題あり")
print("  - 0x40検出されない → PCA9685基板に問題あり")
print()

print("=" * 60)
print("よくある問題パターン")
print("=" * 60)
print()
print("1. IF基板のプルアップ抵抗不足")
print("   - I2Cバスに複数デバイス接続時、プルアップ不足")
print("   - 対策: 外付けで4.7kΩ抵抗追加")
print()
print("2. IF基板の電圧レベル変換問題")
print("   - 5V ↔ 3.3V変換がある場合")
print("   - 変換ICの不良")
print()
print("3. 配線長による信号劣化")
print("   - リボンケーブルが長すぎる")
print("   - I2Cは長距離に弱い（推奨1m以下）")
print()
print("4. GNDループ/ノイズ")
print("   - 複数基板接続時のGNDループ")
print("   - 電源ノイズによる誤動作")
print()

print("=" * 60)
print("次のアクション")
print("=" * 60)
print()
print("優先順位:")
print()
print("1. 【最優先】直接接続テスト（ステップ6）")
print("   → IF基板とPCA9685のどちらに問題があるか特定")
print()
print("2. IF基板の電源・I2C信号測定（ステップ1-3）")
print("   → IF基板が正しく信号を転送しているか確認")
print()
print("3. カウンタボードを外してテスト（ステップ5）")
print("   → 干渉の有無を確認")
print()
