"""
GPIO初期化設定 完全版

カウンターボード + 白線検出 の全GPIOピン

/boot/firmware/config.txt に追加する設定
"""

print("=" * 70)
print("GPIO初期化設定 - 完全版")
print("=" * 70)
print()

print("【設定ファイル編集】")
print()
print("  sudo nano /boot/firmware/config.txt")
print()

print("【追加する設定】")
print()
print("# GPIO初期化設定 (カウンターボード + 白線検出)")
print("# 起動時の電源異常を防止")
print()
print("# 74HC590 カウンタ用")
print("gpio=13=pd  # D0 (QA)")
print("gpio=21=pd  # D1 (QB)")
print("gpio=25=pd  # D2 (QC)")
print("gpio=17=pd  # CCLR (カウンタクリア)")
print("gpio=24=pd  # RCLK (ラッチクロック)")
print()
print("# 74HC74 白線検出用")
print("gpio=23=pd  # Q出力 (読み取り)")
print("gpio=18=pu  # CLR (リセット制御) ← プルアップ")
print()

print("-" * 70)
print()

print("【GPIO18 (CLR) をプルアップにする理由】")
print()
print("  74HC74 CLRはアクティブLOW:")
print("    - HIGH = 通常動作")
print("    - LOW = クリア")
print()
print("  起動時に不定状態になると:")
print("    - LOWになるとQ出力がクリアされる")
print("    - プルアップ (pu) で確実にHIGHを維持")
print()

print("【GPIO23 (Q出力) をプルダウンにする理由】")
print()
print("  74HC74からの入力:")
print("    - 起動時にHi-Z状態の可能性")
print("    - プルダウン (pd) で安定した読み取り")
print()

print("=" * 70)
print("設定手順")
print("=" * 70)
print()
print("1. 設定ファイルを開く:")
print("   sudo nano /boot/firmware/config.txt")
print()
print("2. ファイルの最後に上記の設定を追加")
print()
print("3. 保存: Ctrl+O → Enter → Ctrl+X")
print()
print("4. 再起動: sudo reboot")
print()
print("5. 設定確認:")
print("   raspi-gpio get 18")
print("   → pull=UP と表示されればOK")
print()

print("=" * 70)
print("完全な設定例")
print("=" * 70)
print()
print("/boot/firmware/config.txt の内容:")
print()
print("-" * 70)
print("enable_uart=1")
print("dtoverlay=disable-bt")
print("gpu_mem=64")
print()
print("# GPIO初期化設定 (カウンターボード + 白線検出)")
print("# 起動時の電源異常を防止するため、全制御ピンを初期化")
print()
print("# 74HC590 カウンタ用 (プルダウン)")
print("gpio=13=pd  # D0 (74HC590 QA)")
print("gpio=21=pd  # D1 (74HC590 QB)")
print("gpio=25=pd  # D2 (74HC590 QC)")
print("gpio=17=pd  # CCLR (カウンタクリア)")
print("gpio=24=pd  # RCLK (ラッチクロック)")
print()
print("# 74HC74 白線検出用")
print("gpio=23=pd  # Q出力 (読み取り、プルダウン)")
print("gpio=18=pu  # CLR (リセット制御、プルアップで通常動作維持)")
print("-" * 70)
print()

print("=" * 70)
print("設定後の確認コマンド")
print("=" * 70)
print()
print("全GPIOピンの設定を確認:")
print()
print("  raspi-gpio get 13")
print("  raspi-gpio get 21")
print("  raspi-gpio get 25")
print("  raspi-gpio get 17")
print("  raspi-gpio get 24")
print("  raspi-gpio get 23")
print("  raspi-gpio get 18")
print()
print("期待される出力例:")
print("  GPIO 18: level=1 fsel=0 func=INPUT pull=UP")
print("  GPIO 23: level=0 fsel=0 func=INPUT pull=DOWN")
print()
