"""
手作りカウンターボード（74HC74 + 74HC590）の電源異常診断

【基板構成】
- 74HC74: Dフリップフロップ（白線検出用）
- 74HC590: 8ビットカウンタ（車輪速検出用）
- その他: 受動部品のみ（抵抗、コンデンサ）

【現象】
カウンターボード接続時:
- 5V → 0V
- 3.3V → 4V
"""

print("=" * 60)
print("手作りカウンターボード 電源異常診断")
print("=" * 60)
print()

print("【原因の可能性】")
print()
print("74HC74と74HC590のみの基板で起こりうる問題:")
print()

print("1. ★最も可能性が高い★ VCCピンの配線ミス")
print("   74HC74または74HC590のVCCピンを:")
print("   - 5Vラインと3.3Vラインの両方に接続")
print("   - または配線間でブリッジ")
print()
print("   74HC74 (14ピンDIP):")
print("     Pin 14 = VCC")
print("     Pin 7 = GND")
print()
print("   74HC590 (16ピンDIP):")
print("     Pin 16 = VCC")
print("     Pin 8 = GND")
print()

print("2. プルアップ/プルダウン抵抗の誤配線")
print("   制御ピンのプルアップ抵抗を:")
print("   - 5Vラインと3.3Vラインの両方に接続")
print()
print("   よくある例:")
print("     CCLR ピン ---[10kΩ]--- VCC")
print()
print("   もしVCCが5Vと3.3Vの両方に繋がっていたら短絡")
print()

print("3. 電源バイパスコンデンサの逆接続")
print("   可能性は低いが、極性付きコンデンサの場合:")
print("   - 電解コンデンサの+/-逆")
print()

print("=" * 60)
print("診断手順")
print("=" * 60)
print()

print("【確認1: カウンターボードの配線チェック】")
print()
print("カウンターボードをIF基板から外して、マルチメータで測定:")
print()
print("1. 74HC74 pin 14 (VCC) ↔ 74HC590 pin 16 (VCC)")
print("   測定値: _____ Ω")
print("   正常: 0Ω（両方のVCCは共通接続されるべき）")
print()
print("2. 74HC74 pin 14 (VCC) ↔ 基板の3.3Vコネクタピン")
print("   測定値: _____ Ω")
print("   期待: 0Ω（VCCは3.3Vに接続）")
print()
print("3. 74HC74 pin 14 (VCC) ↔ 基板の5Vコネクタピン")
print("   測定値: _____ Ω")
print("   正常: ∞（VCCは5Vに接続しないはず）")
print("   異常: 0Ω（これが原因！）")
print()
print("4. 基板の5Vコネクタピン ↔ 基板の3.3Vコネクタピン")
print("   測定値: _____ Ω")
print("   正常: ∞（分離されているべき）")
print("   異常: 0Ω～数百Ω（短絡）")
print()

print("【確認2: IC のピン配置確認】")
print()
print("74HC74 (14ピンDIP):")
print("       ┌─────┴─────┐")
print("  CLR1 1│○          │14 VCC ← ここに注目")
print("    D1 2│           │13 CLR2")
print("  CLK1 3│           │12 D2")
print("  SET1 4│  74HC74   │11 CLK2")
print("    Q1 5│           │10 SET2")
print("   Q1' 6│           │9  Q2")
print("   GND 7│           │8  Q2'")
print("       └───────────┘")
print()
print("74HC590 (16ピンDIP):")
print("       ┌─────┴─────┐")
print("   QB 1│○          │16 VCC ← ここに注目")
print("   QC 2│           │15 QA")
print("   QD 3│           │14 SI")
print("   QE 4│           │13 RCLK")
print("   QF 5│  74HC590  │12 G'")
print("   QG 6│           │11 CCLK")
print("   QH 7│           │10 CCLR")
print("  GND 8│           │9  QH'")
print("       └───────────┘")
print()
print("確認事項:")
print("  □ 74HC74 pin 14 の配線先")
print("  □ 74HC590 pin 16 の配線先")
print("  □ 両方が同じVCCラインに接続されているか")
print("  □ そのVCCラインが5Vと3.3Vのどちらか")
print()

print("【確認3: 基板のコネクタピン配置】")
print()
print("IF基板から来る信号:")
print()
print("  Pin | 信号    | 接続先")
print("  ----+---------+------------------")
print("   1  | 5V      | どこに？ _____")
print("   2  | 3.3V    | どこに？ _____")
print("   3  | GND     | 74HC74 pin 7 & 74HC590 pin 8")
print("   4  | D0      | 74HC590 pin 15 (QA)")
print("   5  | D1      | 74HC590 pin 1 (QB)")
print("   6  | D2      | 74HC590 pin 2 (QC)")
print("   7  | CCLR    | 74HC590 pin 10")
print("   8  | RCLK    | 74HC590 pin 13")
print("   9  | 白線    | 74HC74 出力")
print("  ... | ...     | ...")
print()
print("特に重要:")
print("  5Vピンはどこにも接続されていないはず")
print("  3.3VピンがVCCとして使用されるはず")
print()

print("=" * 60)
print("問題のパターン特定")
print("=" * 60)
print()
print("【パターンA: VCCが5Vと3.3Vの両方に接続】")
print()
print("配線例（誤り）:")
print("  IF基板 5V     ───┐")
print("                   ├─── VCC (74HC74 pin 14 & 74HC590 pin 16)")
print("  IF基板 3.3V   ───┘")
print()
print("結果: 5Vと3.3Vが直接短絡 → 異常電圧")
print()

print("【パターンB: プルアップ抵抗経由で短絡】")
print()
print("配線例（誤り）:")
print("  IF基板 5V   ───[10kΩ]─── CCLR ピン")
print("                              |")
print("  IF基板 3.3V ───[10kΩ]───────┘")
print()
print("結果: 抵抗経由で5Vと3.3Vが接続 → 部分的短絡")
print()

print("【パターンC: 配線パターンのブリッジ】")
print()
print("ユニバーサル基板で配線時:")
print("  5Vラインと3.3Vラインが物理的に接触")
print("  はんだブリッジ")
print()

print("=" * 60)
print("対処法")
print("=" * 60)
print()
print("【短期対策】")
print("1. 5Vピンを使用しない")
print("   - IF基板からの5Vラインをカウンターボードに接続しない")
print("   - 3.3VのみでVCC供給（74HCシリーズは2V～6V動作）")
print()
print("2. 問題箇所の切断")
print("   - 短絡箇所が特定できたら物理的に切断")
print("   - はんだ吸取器で修正")
print()

print("【長期対策】")
print("1. 基板の再設計・再製作")
print("   - 配線を見直し")
print("   - 5Vラインを完全に除去（3.3Vのみ使用）")
print()
print("2. レベルシフタの追加")
print("   - 5V系と3.3V系を完全分離")
print("   - ただし今回は不要（3.3Vのみで動作可能）")
print()

print("=" * 60)
print("次のアクション")
print("=" * 60)
print()
print("1. 基板の5Vピン ↔ 3.3Vピンの抵抗測定")
print("   → 短絡しているか確認")
print()
print("2. 74HC74 pin 14 と 74HC590 pin 16 の配線確認")
print("   → どちらに接続されているか（5V or 3.3V）")
print()
print("3. 暫定対策: 5Vピンを切断してテスト")
print("   → 3.3VのみでVCC供給")
print()
