"""
PCA9685基板 診断ガイド

【基板の状態】
- ラズパイから取り外し済み
- ラズパイ側の電源は正常（5V, 3.3V OK）
- 基板側に問題がある可能性

【診断手順】
"""

print("=" * 60)
print("PCA9685基板 診断手順")
print("=" * 60)
print()

print("【ステップ1: 基板の目視確認】")
print()
print("以下を確認してください:")
print("  □ 焼損、変色した部品がないか")
print("  □ ショートの痕跡（黒ずみ、焦げ）がないか")
print("  □ はんだブリッジ（隣接ピン間の短絡）がないか")
print("  □ 部品の脱落、浮きがないか")
print("  □ コンデンサの膨張・液漏れがないか")
print()

print("【ステップ2: 基板単体での抵抗測定】")
print("※ 電源OFF、ラズパイ未接続の状態で測定")
print()
print("1. VCC ↔ GND 間の抵抗")
print("   正常値: 数kΩ～数十kΩ")
print("   異常値:")
print("     - 0Ω～数Ω: 短絡している")
print("     - ∞ (OL): 断線または電源回路の問題")
print()
print("2. SDA ↔ GND 間の抵抗")
print("   正常値: プルアップ抵抗値（通常10kΩ程度）")
print("   異常値: 0Ω（短絡）、∞（断線）")
print()
print("3. SCL ↔ GND 間の抵抗")
print("   正常値: プルアップ抵抗値（通常10kΩ程度）")
print("   異常値: 0Ω（短絡）、∞（断線）")
print()

print("【ステップ3: PCA9685 IC自体の確認】")
print()
print("PCA9685の各ピンとGND間の抵抗を測定:")
print()
print("  Pin 1 (A0)     ↔ GND: 数kΩ～∞")
print("  Pin 25 (SDA)   ↔ GND: 10kΩ程度（プルアップ）")
print("  Pin 26 (SCL)   ↔ GND: 10kΩ程度（プルアップ）")
print("  Pin 27 (VDD)   ↔ GND: 数kΩ～数十kΩ")
print("  Pin 14 (VSS)   ↔ GND: 0Ω（これはGNDピン）")
print()
print("※ 0Ωの箇所が多い場合、IC自体が破損")
print()

print("【ステップ4: 電源レギュレータの確認】")
print("※ 基板に3.3Vレギュレータがある場合")
print()
print("1. レギュレータの型番を確認")
print("   - AMS1117-3.3 など")
print()
print("2. レギュレータのピン電圧（外部5V供給時）")
print("   - 入力ピン: 5V")
print("   - 出力ピン: 3.3V")
print("   - GNDピン: 0V")
print()
print("3. 異常パターン:")
print("   - 入力5V、出力0V → レギュレータ破損")
print("   - 入力0V → 配線ミス")
print()

print("【ステップ5: コネクタピンの確認】")
print()
print("基板のコネクタ（ラズパイ接続部）のピン配置:")
print()
print("  どのピンがVCC、GND、SDA、SCLか確認")
print("  シルク印刷またはピン番号で確認")
print()
print("重要: ピン配置がラズパイと一致しているか")
print("  ラズパイ側:")
print("    物理2p: 5V")
print("    物理3p: GPIO2 (SDA)")
print("    物理5p: GPIO3 (SCL)")
print("    物理6p: GND")
print()

print("【ステップ6: 既知の問題パターン】")
print()
print("1. I2Cプルアップ抵抗の問題")
print("   - SDA/SCLに4.7kΩプルアップが必要")
print("   - 抵抗が無い/断線 → 通信不可")
print()
print("2. 電源キャパシタの問題")
print("   - VCCに100nF～10μFが必要")
print("   - 容量不足 → 不安定動作")
print()
print("3. アドレス設定ピンの問題")
print("   - A0～A5ピンの状態でアドレス決定")
print("   - デフォルト0x40（全てGND）")
print("   - フロートの場合、不定アドレス")
print()

print("=" * 60)
print("測定結果の報告")
print("=" * 60)
print()
print("以下を測定して報告してください:")
print()
print("1. VCC ↔ GND 間の抵抗値: _____ Ω")
print("2. SDA ↔ GND 間の抵抗値: _____ Ω")
print("3. SCL ↔ GND 間の抵抗値: _____ Ω")
print("4. 目視で異常な部品: _____")
print("5. 基板の型番/製造元: _____")
print()
print("【次のアクション】")
print()
print("測定結果に応じて:")
print("  - VCC-GND短絡 → IC破損の可能性、交換検討")
print("  - プルアップ抵抗異常 → 外付け抵抗追加")
print("  - 特定部品の破損 → 部品交換")
print("  - 問題なし → ピン配置の再確認")
print()
