"""
カウンターボード 意図しない5V経路の分析

【前提】
- カウンターボードは3.3Vのみ使用設計
- 74HC74 + 74HC590のみ実装
- 5V電源は基板上で未使用のはず

【現象】
- カウンターボード接続時: 5V→0V、3.3V→4V
- カウンターボード外すと: 正常

【可能性のある意図しない5V経路】
"""

print("=" * 70)
print("意図しない5V経路の分析")
print("=" * 70)
print()

print("【可能性1: ラズパイGPIOからの5V入力（プルアップ経由）★最有力★")
print()
print("ラズパイ側の設定:")
print("  もしGPIOピンがプルアップされていて、その内部プルアップが5Vに接続")
print("  されていた場合、信号線経由で5Vが回り込む可能性")
print()
print("ただし:")
print("  - ラズパイのGPIOは内部プルアップが3.3V系のはず")
print("  - しかしIF基板上に外付けプルアップ抵抗がある可能性")
print()
print("確認ポイント:")
print("  IF基板上のプルアップ抵抗:")
print()
print("    信号ピン例:")
print("      CCLR  ─────[10kΩ]───── VCC (IF基板上)")
print("      RCLK  ─────[10kΩ]───── VCC (IF基板上)")
print("      D0/D1/D2 ─[10kΩ]─── VCC (IF基板上)")
print()
print("    もしIF基板上のVCCが5Vだった場合:")
print("      → 信号線経由でカウンターボードに5Vが流入")
print("      → カウンターボードのVCC(3.3V)と5Vが接続される")
print()

print("【可能性2: IF基板上の配線ミス】")
print()
print("IF基板のコネクタ配線:")
print()
print("  誤った配線例:")
print("    ラズパイ 5V (pin 2/4)")
print("       ↓")
print("    IF基板 5Vライン ───[誤配線]─── 信号ライン")
print("       ↓                              ↓")
print("    カウンター接続ピン          カウンター接続ピン")
print()
print("  可能性:")
print("    - ユニバーサル基板の配線時にジャンパ線が接触")
print("    - はんだブリッジ")
print("    - 意図しない共通ライン")
print()

print("【可能性3: 双方向信号による逆流】")
print()
print("カウンターボード → ラズパイ方向:")
print()
print("  74HC590の出力ピン (QA/QB/QC):")
print("    - 出力がHIGHの時、VCCレベル(3.3V)を出力")
print("    - もしIF基板でこの信号が5Vにプルアップされていたら:")
print()
print("      74HC590 QA (3.3V) ←→ [10kΩ] ←→ 5V (IF基板)")
print()
print("      → 電流が逆流して3.3VラインをVCCに逆注入")
print("      → 3.3Vラインが上昇（4Vへ）")
print()

print("【可能性4: 保護ダイオードの順方向導通】")
print()
print("74HCシリーズの内部構造:")
print()
print("            VCC (3.3V)")
print("             ↑")
print("          [ダイオード] ← 保護ダイオード（内蔵）")
print("             ↑")
print("         入力/出力ピン")
print()
print("もし外部から5Vが入力ピンに印加されたら:")
print("  - 保護ダイオードが順方向導通 (Vf ≈ 0.7V)")
print("  - 5V - 0.7V = 4.3V がVCCラインに逆流")
print("  - 3.3VラインがVCCに接続されているため4Vまで上昇")
print()

print("=" * 70)
print("診断手順")
print("=" * 70)
print()

print("【ステップ1: IF基板のプルアップ抵抗確認】")
print()
print("IF基板を目視で確認:")
print()
print("  □ D0 (GPIO13/pin33) にプルアップ抵抗があるか")
print("  □ D1 (GPIO21/pin40) にプルアップ抵抗があるか")
print("  □ D2 (GPIO25/pin22) にプルアップ抵抗があるか")
print("  □ CCLR (GPIO17/pin11) にプルアップ抵抗があるか")
print("  □ RCLK (GPIO24/pin18) にプルアップ抵抗があるか")
print()
print("  もしプルアップ抵抗があった場合:")
print("    - その抵抗のもう一方はどこに接続？")
print("    - 5Vライン？ それとも3.3Vライン？")
print()
print("  測定方法:")
print("    IF基板単体で:")
print("      D0ピン ↔ 5Vコネクタピン の抵抗: _____ kΩ")
print("      D0ピン ↔ 3.3Vコネクタピン の抵抗: _____ kΩ")
print()
print("    10kΩ程度が測定されたら、そのラインにプルアップあり")
print()

print("【ステップ2: カウンターボード単体での入力保護確認】")
print()
print("カウンターボードを外した状態で:")
print()
print("  74HC590の入力ピン (CCLR/RCLK/CCLK等) に")
print("  外付けプルアップ/プルダウン抵抗があるか確認")
print()
print("  測定:")
print("    CCLR端子 ↔ 基板VCC の抵抗: _____ kΩ")
print("    RCLK端子 ↔ 基板VCC の抵抗: _____ kΩ")
print()
print("  もし抵抗があった場合:")
print("    - その抵抗経由でIF基板の5Vが流入する可能性")
print()

print("【ステップ3: 接続状態での電圧測定】")
print()
print("カウンターボードをIF基板に接続した状態で:")
print()
print("  1. 信号ピンの電圧測定")
print("     D0 (74HC590 pin 15) の電圧: _____ V")
print("     D1 (74HC590 pin 1) の電圧: _____ V")
print("     D2 (74HC590 pin 2) の電圧: _____ V")
print()
print("     もし4V～5Vが測定されたら:")
print("       → 信号線経由で5Vが供給されている")
print()
print("  2. 保護ダイオード導通テスト")
print("     VCC (74HC590 pin 16) の電圧: _____ V")
print("     入力ピン電圧: _____ V")
print()
print("     もし入力ピンがVCCより約0.7V高かったら:")
print("       → 保護ダイオード経由で電流が逆流中")
print()

print("【ステップ4: IF基板の5Vライン追跡】")
print()
print("IF基板のテスター測定:")
print()
print("  ラズパイ側40ピンコネクタ:")
print("    pin 2 (5V) ─────→ どこに配線？")
print("    pin 4 (5V) ─────→ どこに配線？")
print()
print("  カウンターボード側コネクタ:")
print("    どのピンに5Vが来ているか？")
print()
print("  測定:")
print("    IF基板 5Vピン ↔ カウンター接続各ピン")
print("      ピン1: _____ Ω / _____ V")
print("      ピン2: _____ Ω / _____ V")
print("      ピン3: _____ Ω / _____ V")
print("      ...")
print()
print("    0Ωまたは数kΩ～数十kΩで繋がっていたら:")
print("      → そのピンが5V流入経路")
print()

print("=" * 70)
print("推定される問題パターン")
print("=" * 70)
print()

print("【パターンA: IF基板の信号ラインに5Vプルアップ】")
print()
print("  IF基板の配線（誤り）:")
print()
print("    ラズパイ 5V (pin 2)")
print("       ↓")
print("    [10kΩ] ← プルアップ抵抗")
print("       ↓")
print("    D0信号ライン ─────→ カウンターボード 74HC590 pin 15 (QA)")
print("                            ↓")
print("                      保護ダイオード")
print("                            ↓")
print("                          VCC (3.3V)")
print()
print("  結果:")
print("    - 5V → [10kΩ] → QA → 保護ダイオード → VCC")
print("    - 5V - 0.7V = 4.3V が3.3Vラインに注入")
print("    - 3.3Vラインが4Vに上昇")
print()
print("  同時に:")
print("    - 5Vラインから電流が抜ける → 5Vが低下 → 0Vへ")
print()

print("【パターンB: IF基板でVCCが5Vに誤接続】")
print()
print("  IF基板の配線（誤り）:")
print()
print("    ラズパイ 5V (pin 2)")
print("       ↓")
print("    カウンター接続コネクタの「VCC」ピン")
print()
print("  本来は:")
print("    ラズパイ 3.3V (pin 1)")
print("       ↓")
print("    カウンター接続コネクタの「VCC」ピン")
print()
print("  もし誤って5Vに接続されていたら:")
print("    - カウンターボードのVCC(3.3V設計)に5Vが供給")
print("    - 3.3Vラインと5Vラインが直結")
print()

print("=" * 70)
print("緊急対策")
print("=" * 70)
print()

print("【対策1: IF基板の5Vプルアップを除去】")
print()
print("もしIF基板上に5Vへのプルアップ抵抗があったら:")
print("  1. その抵抗を除去")
print("  2. または3.3Vへのプルアップに変更")
print()
print("  例: D0信号ラインのプルアップ")
print("    変更前: D0 ─[10kΩ]─ 5V")
print("    変更後: D0 ─[10kΩ]─ 3.3V")
print()

print("【対策2: カウンターボードにシリーズ抵抗追加】")
print()
print("入力ピンに直列抵抗を追加:")
print()
print("  IF基板 D0 ─[1kΩ]─ カウンター D0入力")
print()
print("  効果:")
print("    - 保護ダイオード経由の逆流電流を制限")
print("    - VCC上昇を抑制")
print()

print("【対策3: IF基板をバイパス（直接接続テスト）】")
print()
print("IF基板を介さずに直接接続:")
print()
print("  ラズパイ 40ピン → ブレッドボード → カウンターボード")
print()
print("  必要な接続:")
print("    pin 1 (3.3V) → カウンターVCC")
print("    pin 6 (GND) → カウンターGND")
print("    pin 33 (GPIO13) → D0")
print("    pin 40 (GPIO21) → D1")
print("    pin 22 (GPIO25) → D2")
print("    pin 11 (GPIO17) → CCLR")
print("    pin 18 (GPIO24) → RCLK")
print()
print("  もしこの構成で正常動作したら:")
print("    → IF基板に問題あり")
print()

print("=" * 70)
print("次のアクション（優先順）")
print("=" * 70)
print()
print("1. IF基板のプルアップ抵抗を目視確認")
print("   → D0/D1/D2/CCLR/RCLK周辺に抵抗があるか")
print("   → その抵抗がどこに接続されているか")
print()
print("2. IF基板単体で抵抗測定")
print("   → D0ピン ↔ 5Vピン の抵抗")
print("   → もし10kΩ程度なら5Vプルアップあり（原因確定）")
print()
print("3. 接続状態での信号ピン電圧測定")
print("   → D0/D1/D2が4V～5Vなら5V供給されている")
print()
print("4. 暫定対策: IF基板の5Vラインを物理切断")
print("   → ラズパイpin 2/4 (5V) への配線をカット")
print("   → PCA9685用に5Vが必要なら別系統で供給")
print()

print("=" * 70)
print("期待される結果")
print("=" * 70)
print()
print("対策後の正常動作:")
print("  - 5V = 5V (正常)")
print("  - 3.3V = 3.3V (正常)")
print("  - PCA9685が0x40で検出可能")
print("  - カウンターボード正常動作")
print()
